In [7]:
from sklearn.linear_model import LinearRegression

In [9]:
from sklearn.cross_validation import train_test_split

In [10]:
model = LinearRegression(normalize = True)

In [11]:
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)


In [12]:
import numpy as np

In [13]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [15]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
y

range(0, 5)

In [17]:
list(y)

[0, 1, 2, 3, 4]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [19]:
X_train

array([[2, 3],
       [8, 9],
       [6, 7]])

In [22]:
y_train

[1, 4, 3]

In [23]:
X_test

array([[0, 1],
       [4, 5]])

In [24]:
y_test

[0, 2]

In [25]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [26]:
predictions = model.predict(X_test)

In [27]:
predictions

array([3.88578059e-16, 2.00000000e+00])